Repository AFKoders/int20h_test, pull requests merged in 2020-01, with the labels that each got.

#3 [Gradle] Fix/ Code rearrangement
  app/build.gradle
Labels: Available for merge :+1:

#1 [Extensions] Feature/ Setup extensions
  app/src/main/java/com/afkoders/musicakinator/utils/ActivityExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/AndroidExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/ButtonExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/RxExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/TextViewExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/ViewExtensions.kt
Labels: Available for merge :+1:

#5 [Styles] Feature/ Common styles
  app/src/main/res/layout/app_toolbar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Code Review needed :man_technologist:

#4 Feature/ Dagger + Networking + Retrofit + Audd.io
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/afkoders/musicakinator/AkinatorApplication.kt
  app/src/main/java/com/afkoders/musicakinator/data/exception/NoConnectivityException.kt
  app/src/main/java/com/afkoders/musicakinator/data/models/FindByLyricsResponse.kt
  app/src/main/java/com/afkoders/musicakinator/data/models/RecognizedSongs.kt
  app/src/main/java/com/afkoders/musicakinator/data/models/Status.kt
  app/src/main/java/com/afkoders/musicakinator/data/retrofit/ConnectivityInterceptor.kt
  app/src/main/java/com/afkoders/musicakinator/data/service/ApiServiceModule.kt
  app/src/main/java/com/afkoders/musicakinator/data/service/AuddApiService.kt
  app/src/main/java/com/afkoders/musicakinator/di/components/ApplicationComponent.kt
  app/src/main/java/com/afkoders/musicakinator/di/modules/ActivityBindingModule.kt
  app/src/main/java/com/afkoders/musicakinator/di/modules/ApplicationModule.kt
  app/src/main/java/com/afkoders/musicakinator/di/modules/NetworkingModule.kt
  app/src/main/java/com/afkoders/musicakinator/di/modules/RxModule.kt
  app/src/main/java/com/afkoders/musicakinator/di/qualifiers/ActivityContext.kt
  app/src/main/java/com/afkoders/musicakinator/di/qualifiers/ApplicationContext.kt
  app/src/main/java/com/afkoders/musicakinator/di/qualifiers/SchedulerIO.kt
  app/src/main/java/com/afkoders/musicakinator/di/qualifiers/SchedulerUI.kt
  app/src/main/java/com/afkoders/musicakinator/di/scope/ActivityScope.kt
  app/src/main/java/com/afkoders/musicakinator/di/scope/ApplicationScope.kt
  app/src/main/java/com/afkoders/musicakinator/di/scope/FragmentScope.kt
  app/src/main/java/com/afkoders/musicakinator/utils/AndroidExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/NullOrEmptyConverterFactory.kt
Labels: Code Review needed :man_technologist:

#7 [Styles] Feature/ Setup styles by design
  app/src/main/res/drawable/ic_clean.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_history.xml
  app/src/main/res/drawable/ic_micro.xml
  app/src/main/res/drawable/ic_pause_music.xml
  app/src/main/res/drawable/ic_play_music.xml
  app/src/main/res/drawable/radial_gradient.xml
  app/src/main/res/font/druk_wide_bold.otf
  app/src/main/res/font/druk_wide_heavy.otf
  app/src/main/res/font/druk_wide_medium.otf
  app/src/main/res/font/druk_wide_super.otf
  app/src/main/res/font/maven_pro_black.ttf
  app/src/main/res/font/maven_pro_bold.ttf
  app/src/main/res/font/maven_pro_extra_bold.ttf
  app/src/main/res/font/maven_pro_medium.ttf
  app/src/main/res/font/maven_pro_regular.ttf
  app/src/main/res/font/maven_pro_semi_bold.ttf
  app/src/main/res/layout/app_toolbar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Available for merge :+1:

#6 [Navigation] Feature/ Implemented nav graph and created fragments
  app/src/main/java/com/afkoders/musicakinator/presentation/MainActivity.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/ask_me/AskMeFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/ask_me/AskMeViewModel.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/found_song/FoundSongFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/found_song/FoundSongViewModel.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/game_result/GameResultFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/game_result/GameResultViewModel.kt
  app/src/main/res/anim/enter_from_left.xml
  app/src/main/res/anim/enter_from_right.xml
  app/src/main/res/anim/enter_from_top.xml
  app/src/main/res/anim/exit_to_left.xml
  app/src/main/res/anim/exit_to_right.xml
  app/src/main/res/anim/exit_to_top.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_ask_me.xml
  app/src/main/res/layout/fragment_found_song.xml
  app/src/main/res/layout/fragment_game_result.xml
  app/src/main/res/navigation/akinator_nav_graph.xml
Labels: Available for merge :+1:

#9 [Vector] Feature/ Add new vector asset for slider
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_slider_point.xml
Labels: Available for merge :+1:

#2 [Base Classes] Feature/ Abstraction setup
  app/build.gradle
  app/src/main/java/com/afkoders/musicakinator/AkinatorApplication.kt
  app/src/main/java/com/afkoders/musicakinator/data/exception/NoResultException.kt
  app/src/main/java/com/afkoders/musicakinator/data/models/FindByLyricsResponse.kt
  app/src/main/java/com/afkoders/musicakinator/data/models/Song.kt
  app/src/main/java/com/afkoders/musicakinator/data/repository/AuddRepository.kt
  app/src/main/java/com/afkoders/musicakinator/data/repository/AuddRepositoryImpl.kt
  app/src/main/java/com/afkoders/musicakinator/data/repository/RepositoryModule.kt
  app/src/main/java/com/afkoders/musicakinator/data/retrofit/ConnectivityInterceptor.kt
  app/src/main/java/com/afkoders/musicakinator/data/service/ApiServiceModule.kt
  app/src/main/java/com/afkoders/musicakinator/data/service/AuddApiService.kt
  app/src/main/java/com/afkoders/musicakinator/di/components/ApplicationComponent.kt
  app/src/main/java/com/afkoders/musicakinator/di/modules/ActivityBindingModule.kt
  app/src/main/java/com/afkoders/musicakinator/di/modules/ApplicationModule.kt
  app/src/main/java/com/afkoders/musicakinator/di/modules/NetworkingModule.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/BaseFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/MainActivity.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/MainActivityModule.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/ViewModelModule.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/akinator_lose/AkinatorLoseFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/akinator_won/AkinatorWonFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/akinator_won/AkinatorWonViewModel.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/ask_me/AskMeFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/found_song/FoundSongFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/found_song/FoundSongViewModel.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/game_result/GameResultFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/game_result/GameResultViewModel.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/search/SearchFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/search/SearchViewModel.kt
  app/src/main/java/com/afkoders/musicakinator/utils/ViewModelFactory.kt
  app/src/main/java/com/afkoders/musicakinator/utils/extensions/ActivityExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/extensions/AndroidExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/extensions/ButtonExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/extensions/RxExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/extensions/TextViewExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/extensions/ViewExtensions.kt
  app/src/main/res/layout/fragment_akinator_lose.xml
  app/src/main/res/layout/fragment_akinator_won.xml
  app/src/main/res/layout/fragment_found_song.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/navigation/akinator_nav_graph.xml
  gradle.properties
Labels: Code Review needed :man_technologist:

#10 [Translations] Feature/ Add Cyrillic languages translations
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: Code Review needed :man_technologist:

#12 Deezer SDK works, can find song and show it to user
  app/build.gradle
  app/src/main/java/com/afkoders/musicakinator/presentation/MainActivity.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/found_song/FoundSongFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/found_song/FoundSongViewModel.kt
  app/src/main/res/layout/fragment_found_song.xml
  deezer-sdk-0.11.2/build.gradle
  deezer-sdk-0.11.2/deezer-sdk-0.11.2.aar
  settings.gradle
Labels: Child :baby:

#13 [Screens] Feature/ Result screen testing
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/java/com/afkoders/musicakinator/presentation/MainActivityModule.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/ViewModelModule.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/akinator_lose/AkinatorLoseFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/akinator_won/AkinatorWonFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/akinator_won/AkinatorWonViewModel.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/found_song/FoundSongFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/found_song/FoundSongViewModel.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/Interaction.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/InteractionViewModel.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/Intermix.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/failure/FailureFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/retry/RetryFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/success/SuccessFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_found_song.xml
  app/src/main/res/navigation/akinator_nav_graph.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: Code Review needed :man_technologist:

#16 Search history / found song layout
  app/src/main/java/com/afkoders/musicakinator/presentation/MainActivityModule.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/ViewModelModule.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/found_song/FoundSongFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/history/HistoryAdapter.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/history/HistoryFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/history/HistoryViewModel.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/search/SearchFragment.kt
  app/src/main/java/com/afkoders/musicakinator/utils/prefs/HistoryPrefs.kt
  app/src/main/java/com/afkoders/musicakinator/utils/prefs/PrefsModel.kt
  app/src/main/res/drawable/gradient_found_song.xml
  app/src/main/res/layout/fragment_found_song.xml
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/history_item.xml
  app/src/main/res/navigation/akinator_nav_graph.xml
  app/src/main/res/values/colors.xml
Labels: Available for merge :+1:

#17 [Styles] Feature/ Style adjustments
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Code Review needed :man_technologist:

#18 Fix/ Dagger for preferences
  app/src/main/java/com/afkoders/musicakinator/data/prefs/HistoryModel.kt
  app/src/main/java/com/afkoders/musicakinator/data/prefs/HistoryPrefs.kt
  app/src/main/java/com/afkoders/musicakinator/di/modules/ApplicationModule.kt
  app/src/main/java/com/afkoders/musicakinator/di/modules/RxModule.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/BaseFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/found_song/FoundSongFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/history/HistoryAdapter.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/history/HistoryFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/history/HistoryViewModel.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/failure/FailureFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/retry/RetryFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/success/SuccessFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/search/SearchFragment.kt
  app/src/main/java/com/afkoders/musicakinator/utils/prefs/HistoryPrefs.kt
  app/src/main/res/drawable/gradient_found_song.xml
  app/src/main/res/layout/fragment_found_song.xml
  app/src/main/res/navigation/akinator_nav_graph.xml
  app/src/main/res/values/colors.xml
Labels: Available for merge :+1:

#21 Feature/search screen improvements
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/afkoders/musicakinator/di/modules/ApplicationModule.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/MainActivity.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/ViewModelModule.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/found_song/FoundSongFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/search/SearchFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/search/SearchViewModel.kt
  app/src/main/java/com/afkoders/musicakinator/utils/speechRecognition/SpeechRecognitionHelper.kt
  app/src/main/res/drawable/ic_close_gray.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/navigation/akinator_nav_graph.xml
  app/src/main/res/values/colors.xml
Labels: Available for merge :+1:

#20 [Styles] Feature/ Add Chips
  app/build.gradle
  app/src/main/java/com/afkoders/musicakinator/data/service/AuddApiService.kt
  app/src/main/java/com/afkoders/musicakinator/data/service/DeezerApiService.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/MainActivityModule.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/ViewModelModule.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/found_song/FoundSongFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/found_song/FoundSongViewModel.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/InteractionViewModel.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/loading/LoadingFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/retry/RetryFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/success/SuccessFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/search/SearchFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/search/SearchViewModel.kt
  app/src/main/res/color/tab_chip_background.xml
  app/src/main/res/color/tab_chip_text_color.xml
  app/src/main/res/drawable/gradient_found_song.xml
  app/src/main/res/drawable/radial_gradient.xml
  app/src/main/res/layout/fragment_found_song.xml
  app/src/main/res/layout/fragment_result_success.xml
  app/src/main/res/navigation/akinator_nav_graph.xml
  app/src/main/res/values/styles.xml
Labels: Available for merge :+1:

#26 History
  app/src/main/java/com/afkoders/musicakinator/data/prefs/History.kt
  app/src/main/java/com/afkoders/musicakinator/data/prefs/HistoryModel.kt
  app/src/main/java/com/afkoders/musicakinator/data/prefs/HistoryPrefs.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/found_song/FoundSongFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/history/HistoryAdapter.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/history/HistoryFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/history/HistoryViewModel.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/Interaction.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/InteractionViewModel.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/Intermix.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/loading/LoadingFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/retry/RetryFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/success/SuccessFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/search/SearchFragment.kt
  app/src/main/res/drawable/gradient_history.xml
  app/src/main/res/drawable/iv_rectangle_with_corners_dark.xml
  app/src/main/res/layout/exo_playback_control_view.xml
  app/src/main/res/layout/fragment_found_song.xml
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_result_failure.xml
  app/src/main/res/layout/fragment_result_retry.xml
  app/src/main/res/layout/fragment_result_success.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/history_item.xml
  app/src/main/res/navigation/akinator_nav_graph.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Available for merge :+1:

#28 [Git] Fix/ Merge fixes
  app/src/main/java/com/afkoders/musicakinator/presentation/found_song/FoundSongFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/history/HistoryAdapter.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/InteractionViewModel.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/Intermix.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/success/SuccessFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/search/SearchFragment.kt
  app/src/main/java/com/afkoders/musicakinator/utils/extensions/AndroidExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/extensions/ButtonExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/extensions/FragmentExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/extensions/TextViewExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/extensions/ViewExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/extensions/widget/EditTextExtensions.kt
  app/src/main/res/drawable/gradient_history.xml
  app/src/main/res/drawable/ic_deezer_logo.xml
  app/src/main/res/layout/exo_playback_control_view.xml
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_loading.xml
  app/src/main/res/layout/fragment_result_success.xml
  app/src/main/res/layout/history_item.xml
Labels: Code Review needed :man_technologist:

#29 FIXES
  app/src/main/java/com/afkoders/musicakinator/presentation/found_song/FoundSongFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/search/SearchFragment.kt
  app/src/main/res/layout/exo_playback_control_view.xml
  app/src/main/res/layout/fragment_found_song.xml
  app/src/main/res/layout/fragment_result_success.xml
Labels: Available for merge :+1:

#30 [Fixes] Fix/ close latest bugs
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/afkoders/musicakinator/data/models/Album.kt
  app/src/main/java/com/afkoders/musicakinator/data/models/DeezerSong.kt
  app/src/main/java/com/afkoders/musicakinator/data/prefs/HistoryPrefs.kt
  app/src/main/java/com/afkoders/musicakinator/data/repository/AuddRepositoryImpl.kt
  app/src/main/java/com/afkoders/musicakinator/data/service/DeezerApiServiceModule.kt
  app/src/main/java/com/afkoders/musicakinator/di/modules/ActivityBindingModule.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/BaseFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/MainActivity.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/custom/AudioProgressBar.java
  app/src/main/java/com/afkoders/musicakinator/presentation/found_song/FoundSongFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/history/HistoryAdapter.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/history/HistoryFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/history/HistoryViewModel.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/Intermix.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/interation_with_akinator/success/SuccessFragment.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/search/SearchFragment.kt
  app/src/main/java/com/afkoders/musicakinator/utils/extensions/widget/EditTextExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/speechRecognition/SpeechRecognitionHelper.kt
  app/src/main/res/drawable/gradient_history.xml
  app/src/main/res/drawable/ic_close_gray.xml
  app/src/main/res/drawable/ic_delete_history.xml
  app/src/main/res/drawable/round_rect.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/exo_playback_control_view.xml
  app/src/main/res/layout/fragment_found_song.xml
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  deezer-sdk-0.11.2/build.gradle
  deezer-sdk-0.11.2/deezer-sdk-0.11.2.aar
  settings.gradle
Labels: :no_entry_sign: DO NOT MERGE, Available for merge :+1:

#33 [Fixes] Adjustments/ Clean up
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-web.png
  app/src/main/java/com/afkoders/musicakinator/data/prefs/HistoryPrefs.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/MainActivity.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/history/HistoryAdapter.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/history/HistoryViewModel.kt
  app/src/main/java/com/afkoders/musicakinator/presentation/search/SearchFragment.kt
  app/src/main/java/com/afkoders/musicakinator/utils/extensions/ActivityExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/extensions/AndroidExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/extensions/FragmentExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/extensions/RxExtensions.kt
  app/src/main/java/com/afkoders/musicakinator/utils/extensions/widget/ButtonExtensions.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/cursor.xml
  app/src/main/res/drawable/ic_close_gray.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/exo_playback_control_view.xml
  app/src/main/res/layout/fragment_found_song.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Code Review needed :man_technologist:

#36 Added keystore, APK and fixed strings
  .gitignore
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
  keystore/afkoders
  preview/AFKoders-Music-Akinator-v1.0.0-release.apk
Labels: Available for merge :+1:
